### ISSUE TITLE
Find should take `&self` and not `&mut self`

### ISSUE THREAD

**Issue by lenianiva** [gifnksm/union-find-rs#20]
```rust
    /// Returns the identifier of the set that the key belongs to.
    fn find(&mut self, key: usize) -> usize;
```
There is no reason for this to take `&mut self`.

**Comment by gifnksm** [comment]
Some algorithms may update the data structure on `find`.

For example, `QuickUnionUF` in this repository updates the tree structure on `find`.

https://github.com/gifnksm/union-find-rs/blob/2e1d606eea83d52cd57793078231197f6bbde3d9/src/quick_union.rs#L71-L81
