### ISSUE TITLE
The documentation link on crates.io leads to a 404

### ISSUE THREAD

**Issue by JSorngard** [gifnksm/union-find-rs#24]
When following the documentation link on crates.io (https://gifnksm.github.io/union-find-rs) the result is a 404 page:
![bild](https://github.com/user-attachments/assets/ff0ccbc1-4319-4308-9f09-78316b9636f8)

**Comment by JSorngard** [comment]
I mean the link in the sidebar: 
![bild](https://github.com/user-attachments/assets/6c3b8626-6567-4aa9-82f8-56af0f0d90f3)

The link to docs.rs in the readme works as normal.

**Comment by gifnksm** [comment]
Thank you for reporting!
The crates.io link will be fixed in the next release.
